name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: pnpm/action-setup@v2.4.0
      - uses: actions/setup-node@v4.0.0
        with:
          node-version: latest
          cache: pnpm

      - run: pnpm install
      - run: pnpm run lint
      - run: pnpm run test
      - run: pnpm run build

      - uses: codecov/codecov-action@v3.1.4
