name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0

      - uses: pnpm/action-setup@v2.4.0
      - uses: actions/setup-node@v3.8.2
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm

      - run: pnpm install
      - run: pnpm run build
      - run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
